### ISSUE TITLE
ros2 run rclcpp_components component_container hangs starting up

### ISSUE THREAD

**Issue by KenYN** [ros2/rclcpp#1800]
## Bug report

**Required Info:**
- Operating System:
  - Ubuntu 20.04 in Docker on Ubuntu 20.04 -->
- Installation type:
  - Binaries
- Version or commit hash:
  - Galactic
- DDS implementation:
  - Default DDS
- Client library (if applicable):
  - NA

#### Steps to reproduce issue

Just typing this:
```
ros2 run rclcpp_components component_container
```

#### Expected behavior
The command completes - not sure what exactly should be output.

#### Actual behavior
I get a message like
```
1634029897.915359 [0] component_: using network interface enp4s0f2 (udp/10.208.6.84) selected arbitrarily from: enp4s0f2, docker0
```

And nothing more happens. Processor time is 0%. If I hit control+C, I see this, but it doesn't exit:
```
^C[INFO] [1634030026.572906048] [rclcpp]: signal_handler(signal_value=2)
```

#### Additional information
`ros2 component list` hangs similarly with the nextwork interface message, but `ros2 component types` succeeds.

**Comment by clalancette** [comment]
> ros2 run rclcpp_components component_container

So this command will never complete, by design.  As its name suggests, it is a container for other components to be loaded into; see https://docs.ros.org/en/galactic/Tutorials/Composition.html for an example on how to use it.

> If I hit control+C, I see this, but it doesn't exit:

It should always exit, and it does for me.  `ros2 component list` also succeeds for me.  I think you'll need to describe more about your configuration, including your network setup for docker.

**Comment by KenYN** [comment]
My Foxy Docker seems to work OK, but Galactic hangs. My `dockerfile` is highly customised, so I cannot share it here, but for now I suspect the problem is something very local to my setup, so I'll close this for now.
