### ISSUE TITLE
Request: Provide examples for enduser

### ISSUE THREAD

**Issue by firesurfer** [ros2/rclcpp#241]
As said in #240 I would really appreciate some simple examples that demonstrate how to use the build system properly. 

Especially an xample CMakeLists.txt (or complete package) would be usefull that shows how to:
- Build a simple program against the default rosmiddleware (The given examples are all built against all middlewares - I don't think that an enduser wants to build his code against all middlewares in most cases)
- Build messages and program in the same package

Overall some documentation/examples that show how the enduser (by enduser I mean the developer that uses ros2 for his own implementation) is intended to use the ament build system would be nice. The current documentation on ament that I found is a bit spare.

**Comment by Karsten1987** [comment]
@firesurfer I believe you can find a simple example of a CMakeLists.txt in [here](https://github.com/ros2/examples/blob/master/rclcpp/minimal_publisher/CMakeLists.txt).

I am going to close this issue because I think it is not related to rclcpp. Please feel free to open another issue, e.g. on the examples repo if you think these can be improved or made clearer.
