### ISSUE TITLE
Use std::vector to store publisher shared_ptrs

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rclcpp#430]
Should I implement my own STL allocator to store ,say suppose , a vector of publisher shared_ptrs pointing to different message structures(sensor/std/geometry etc.). It seems using the std::vector doesn't work ( compilation errors) for storing these shared pointers..

**Comment by wjwwood** [comment]
You cannot store publishers of different message types in a vector, since they’re templated on the message type and are therefore not the same type and std vector only stores homogeneous types. However, you can store a vector of `rclcpp::PublisherBase` which is the common base class for all publishers.
