### ISSUE TITLE
Add more callbacks to rclcpp_action::Client

### ISSUE THREAD

**Issue by stertingen** [ros2/rclcpp#635]
#### Feature description
Using the action client in `rclcpp_action` requires polling using timers on the future objects returned by `Client::async_send_goal` and `Client::async_get_result`. It would be far more convenient to add callbacks to these functions.

(```spin_until_future_complete``` won't work because my node is already spinning.)

#### Implementation considerations

Possible function signatures could look like this:
```
using GoalResultCallback =
  std::function<void(std::shared_future<typename GoalHandle::SharedPtr>)>;
using ResultCallback =
  std::function<void(std::shared_future<Result>)>;

std::shared_future<typename GoalHandle::SharedPtr>
async_send_goal(
  const Goal & goal, GoalResultCallback = nullptr,
  FeedbackCallback callback = nullptr, ResultCallback = nullptr,
  bool ignore_result = false);

std::shared_future<Result>
async_get_result(typename GoalHandle::SharedPtr goal_handle, ResultCallback = nullptr)
```

While these are the callbacks I currently need, it would be consistent to add appropriate callbacks to all functions returning future objects.

**Comment by jacobperron** [comment]
This seems like a reasonable addition.

Until a mechanism like [std::future::then](https://en.cppreference.com/w/cpp/experimental/future/then) is available, future objects are of limited use. I suspect this is why the [service client also takes a callback parameter](https://github.com/ros2/rclcpp/blob/3919ab189795fbf47b5427add06f45d8a43f81ce/rclcpp/include/rclcpp/client.hpp#L231).

A PR is welcome for the proposed change :slightly_smiling_face: 

---

An alternative to the issue is to refactor the spin functions so that it is possible to recursively spin on futures. I noticed a TODO in the code:

https://github.com/ros2/rclcpp/blob/3919ab189795fbf47b5427add06f45d8a43f81ce/rclcpp/include/rclcpp/executor.hpp#L227-L228

I haven't thought too much about how this might be done though.
