### ISSUE TITLE
Proposal for NodeHandle concept that simplifies calling APIs with node-like objects

### ISSUE THREAD

**Issue by sloretz** [ros2/rclcpp#831]
#### Feature description
This is an idea to simplify code that calls APIs using node interfaces. It proposes adding template classes `NodeHandle<>` and `NodeHandle<>::SharedPtr` who are given placeholder types that indicate the needed node interfaces.

##### When node interfaces are just needed for the lifetime of the call

`create_service()` needs a [`NodeBaseInterface` and `NodeServicesInterface`](https://github.com/ros2/rclcpp/blob/17841d6b7cff96efef87400fee2dcd63a6f10101/rclcpp/include/rclcpp/create_service.hpp#L34-L36). It doesn't need shared pointers to these interfaces; it just needs them for the duration of the call.

Before:

```c++
create_service(
  std::shared_ptr<node_interfaces::NodeBaseInterface> node_base,
  std::shared_ptr<node_interfaces::NodeServicesInterface> node_services,
  // ...

// User calls with
auto service = create_service(
  my_node_class->get_node_base_interface(),
  my_node_class->get_node_services_interface(),
  // ...
```

after

```c++
create_service(
     rclcpp::NodeHandle<Base, Services> node_handle,
     // ...

// User calls with
auto service = create_service(
  my_node_class,
  // ...
```

##### When node interfaces are needed long term

[`tf2_ros::TransformListener` needs the node base interface](https://github.com/ros2/geometry2/blob/4e519f3e77611a18f03398b6334e9cc8ccf49552/tf2_ros/include/tf2_ros/transform_listener.h#L104) for a long time, so it holds a shared pointer.

It currently does some logic in the header file and some in the cpp file, but the intent of this proposal is to enable moving all of it to the cpp file.

Before
```C++
  TransformListener(
    tf2::BufferCore & buffer,
    NodeT && node,
    // ...
    // in header creates subscription and calls initThread(node->get_node_base_interface()); to store shared pointer to node
```

After

```c++
  TransformListener(
    tf2::BufferCore & buffer,
    rclcpp::NodeHandle<Base, Subscription>::SharedPtr node_handle,
    // ...
    );  // Just declaration in header
```

#### Implementation considerations

Placeholder types should be created for each node interface. The purpose of these is to make the type of a `NodeHandle` more readable. In my opinion `rclcpp::NodeHandle<Base>` is easier to read than `rclcpp::NodeHandleBase<node_interfaces::NodeBaseInterface>`.

The types passed to `NodeHandle<>` would indicate the interfaces needed by a method. `rclcpp::NodeHandle<Base, Topics>` would replace [`get_node_base_interface`](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/node_interfaces/get_node_base_interface.hpp) and [`get_node_topics_interface()`](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/node_interfaces/get_node_topics_interface.hpp). Using similar template magic, it would get the base and topics interface off of whatever it's given at compile time. Code would access the interfaces with `node_handle.base()` or `node_handle.topics()` and those would return raw pointers to the interfaces.

`rclcpp::NodeHandle<Base, Topics>::SharedPtr` is a little more interesting because `get_node_*_interface()` don't address this use case, and I've seen it a couple times while porting packages. Some API's need shared pointers to the node interfaces so they can keep them alive for a while. `NodeHandle<>::SharedPtr` should be a shared pointer to an object that holds shared pointers to the interfaces. Interfaces would be accessed via `node_handle->base()` and `node_handle->topics()`, but the return type would be a shared pointer instead of a raw pointer. Since the return type is different, this is probably a different class internally (`NodeHandle<>::SharedPtr = std::shared_ptr<NodeHandleCopyable<>>`).

**Comment by wjwwood** [comment]
In your example, does `my_node_class`'s type inherit from `rclcpp::NodeHandle<Base, Services>`?

How is this different from `std::pair<...Base..., ...Services...>`?

How does `rclcpp::NodeHandle<>::SharedPtr` work? Does `rclcpp::NodeHandle<>` not also need to keep handles to the interface's shared pointers? In that case could you not just copy the instance of `rclcpp::NodeHandle<>` rather than putting it in a shared poitner?

What would happen if the interfaces were coming two places? Like if instead of a node class which has a Base and Services interface inside it, I instead had just a MockBase and MockServices as separate objects? Can a `rclcpp::NodeHandle<Base, Services>` be created from parts?

How does this overlap with or work along with these existing helper functions:

- https://github.com/ros2/rclcpp/blob/64c0f86f14dfe2337816079c4d5991268aeb0635/rclcpp/include/rclcpp/node_interfaces/get_node_base_interface.hpp#L120-L144
- https://github.com/ros2/rclcpp/blob/64c0f86f14dfe2337816079c4d5991268aeb0635/rclcpp/include/rclcpp/node_interfaces/get_node_timers_interface.hpp#L120-L144
- https://github.com/ros2/rclcpp/blob/64c0f86f14dfe2337816079c4d5991268aeb0635/rclcpp/include/rclcpp/node_interfaces/get_node_topics_interface.hpp#L120-L144

Which are used like this:

- https://github.com/ros2/rclcpp/blob/c769b1b03032d6789daa6d075cf63e955079953c/rclcpp/include/rclcpp/create_publisher.hpp#L82

**Comment by ivanpauno** [comment]
I'm ok with any of the styles proposed, maintaining the current helper functions or creating a `NodeHandle` template class magic (I haven't think much of how the implementation would look and if that's possible at all), but I have some concerns with the current helper functions:

- The helper functions look if the object has a `get_*_interface` method returning a raw pointer or a shared pointer, and in any of both cases it returns a raw pointer.
  https://github.com/ros2/rclcpp/blob/64c0f86f14dfe2337816079c4d5991268aeb0635/rclcpp/include/rclcpp/node_interfaces/get_node_base_interface.hpp#L29-L33
  (I copied the doc, but the code is actually doing that).
  That limits user that may want to retain part ownership of the interfaces.
  We're currently doing that in some places, and not using this helper functions because they return a raw pointer.
  And actually, all our `get_*_interface` methods in "Node like" classes return a shared pointer (I haven't found any returning a raw pointer), so we could return it.
  If someone wants a raw pointer, they can then call `get`.

- The helper functions accepts any of a shared pointer, a raw pointer or a universal reference to a "Node like" object.
  I don't see any value of doing that.
  The functions aren't retaining part ownership of the shared pointer, so it shouldn't be accepted.
  Accepting a raw pointer doesn't have much sense to me.
  I would only accept a universal reference to a "Node like" object.

----

Examples of places where we're not using the helper functions (in some of them, they need a shared pointer and not a raw pointer):

- https://github.com/ros2/geometry2/blob/094d363a5b5d4d22b2ac3d4b586dc487079f7338/tf2_ros/include/tf2_ros/transform_listener.h#L75-L103

- https://github.com/ros/diagnostics/blob/678ac48626d0357dc64e858028d497422fcbe19c/diagnostic_updater/include/diagnostic_updater/diagnostic_updater.hpp#L365-L382

- https://github.com/ros2/rclcpp/blob/64c0f86f14dfe2337816079c4d5991268aeb0635/rclcpp_components/include/rclcpp_components/node_factory_template.hpp#L31-L48

----

I left some similar comments in a related discussion that proposed another alternative for this (adding an [is_pointer](https://github.com/ros2/rcpputils/pull/19) thing):
https://github.com/ros2/rclcpp/pull/817#issuecomment-518753165 and https://github.com/ros2/rclcpp/pull/817#issuecomment-521628467

**Comment by wjwwood** [comment]
I think that's all fair feedback about the existing methods. They sort of evolved into that. I think always taking a NodeT & (not pointer or shared pointer) is ok (though Node's are basically always shared pointers right now), and always returning a shared pointer (or at least having a separate function that can do that) to the interface object is also a good idea to limit what's possible.

**Comment by methylDragon** [comment]
I think we can close this issue with the merge of https://github.com/ros2/rclcpp/pull/2041
