### ISSUE TITLE
rclcpp_action: async_send_goal makes the goal handle available to caller before making it result aware

### ISSUE THREAD

**Issue by astere-cpr** [ros2/rclcpp#955]
In client.hpp:375 the action client sets the value of the goal handle promise, making the goal handle available to the caller via the goal handle future. The goal handle is made result aware a few lines further down in client.hpp:382.

If client code calls async_result() on the goal handle from a user thread that gets scheduled after the promise value was set but before the goal was made result aware, async_result() will throw an UnawareGoalHandleException.

**Comment by jacobperron** [comment]
@astere-cpr 
You're right, there is a race existing in the implementation. This was brought up previously (but forgotten about): https://github.com/ros2/rclcpp/pull/701/files#r278256708

Correct me if I'm wrong, but I think if you call the client's method, [`async_get_result`](https://github.com/ros2/rclcpp/blob/d2723fb1594eb3c40dafb5fd930b52c6e42e50eb/rclcpp_action/include/rclcpp_action/client.hpp#L400-L403), instead of the goal handle's method then it avoids this race.

IMO, it makes sense to just provide the client interface for requesting the goal result and the goal handles method should not be exposed to the user. Unless there's a use-case that I'm missing.
If you agree, we can deprecate the public API [async_result](https://github.com/ros2/rclcpp/blob/d2723fb1594eb3c40dafb5fd930b52c6e42e50eb/rclcpp_action/include/rclcpp_action/client_goal_handle.hpp#L102-L103), as it is not thread safe.

**Comment by jacobperron** [comment]
See https://github.com/ros2/rclcpp/pull/1120, which deprecates the use of `async_result`.
